import Head from 'next/head'
import styles from '../styles/game.module.css'

export default function Game() {

    return (
      <div>
        <Head>
            <title>Pixieland | Game</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
      <main className={`${styles.main}`}>
        <div className={`${styles.comingsoon}`}>
          COMING SOON
        </div>
      </main>
      </div>  
      </div>
    )
  }