import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pixieland | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        <a href="/">Pixieland</a>
        </h1>
        <h2 className={styles.head }>
          <a href="/game">PLAY</a>
        </h2>
      </main>

      <div className={styles.other}>
        <div style={{paddingRight:"300px"}}>
          <div className={styles.griditem} style={{justifyContent:"center", alignItems:"center"}}>
            Image Here
          </div>
        </div>
        <div>  
          <div className={styles.griditem} style={{textAlign:"left", paddingLeft:"20px", paddingRight:"20px"}}>
            <h1 style={{borderBottom:"2px solid black"}}>
              Title
            </h1>
            <p>
              text
            </p>
          </div>  
        </div>
      </div>

    
      <div className={styles.other} style={{paddingTop:"300px", paddingBottom:"400px"}}>
        <div style={{paddingRight:"300px"}}>
          <div className={styles.griditem} style={{textAlign:"right", padding:"0px 20px 0px 20px"}}>
            <h1 style={{borderBottom:"2px solid black"}}>
              Title
            </h1>
            <p>
              text
            </p>
          </div>
        </div>
        <div>  
          <div className={styles.griditem} style={{}}>
            Image here
          </div>  
        </div>
        </div>

    </div>
  )
}


