import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pixieland | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div>
      <main className={styles.main}>
        <h1 className={styles.title} >
        <a href="/" style={{fontFamily:"ChronoType"}}>Pixieland</a>
        </h1>
        <h2 className={styles.head }>
          <div className={styles.playbutton}><a href="/game">PLAY</a></div>
        </h2>
      </main>
      </div>


      <div className={styles.other}>
        <div style={{paddingRight:"300px"}}>
          <div className={styles.griditem} style={{justifyContent:"center", alignItems:"center"}}>
            <img src='firesnowhouse.gif' style={{transform:"scale(30%) translateY(-1000px) translateX(-1150px)", borderRadius: "20px", boxShadow:"-4px -3px 45px 21px rgba(0,0,0,0.35)"}}/>
          </div>
        </div>
        <div>  
          <div className={styles.griditem} style={{textAlign:"left", paddingLeft:"20px", paddingRight:"20px"}}>
            <h1 style={{borderBottom:"2px solid black"}}>
              Title
            </h1>
            <p style={{fontFamily:"Pixelboy"}}> 
              text
            </p>
          </div>  
        </div>
      </div>

    
      <div className={styles.other} style={{paddingTop:"300px", paddingBottom:"400px"}}>
        <div style={{paddingRight:"300px"}}>
          <div className={styles.griditem} style={{textAlign:"right", padding:"0px 20px 0px 20px"}}>
            <h1 style={{borderBottom:"2px solid black"}}>
              Title
            </h1>
            <p>
            <div style={{fontFamily:"Pixelboy"}}>
        text
        </div>
            </p>
          </div>
        </div>
        <div>  
          <div className={styles.griditem} style={{}}>
          <img src='abandonedhouse.png' style={{transform:"scale(30%) translateY(-1000px) translateX(-1150px)", borderRadius: "20px", boxShadow:"-4px -3px 45px 21px rgba(0,0,0,0.35)"}}/>
          </div>  
        </div>


        </div>

    </div>
  )
}


