import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head> 
        <title>Pixieland | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div>
     
      <main className={styles.main}>
        <h1 className={styles.title}>
        <a href="/" style={{fontFamily:"ChronoType"}}>Pixieland</a>
        </h1>
        <h2 className={styles.head } >
          <div className={styles.playbutton}><a href="/game">PLAY</a></div>
        </h2>
      </main>
      </div>

      <div className={styles.scrollingimgs}>
        <Image src='/420.gif' width={400} height={400}/>
        <Image src='/421.gif' width={400} height={400}/>
        <Image src='/1424.gif' width={400} height={400}/>
        <Image src='/1581.gif' width={400} height={400}/>
        <Image src='/1824.gif' width={400} height={400}/>
        <Image src='/3824.gif' width={400} height={400}/>
        <Image src='/420.gif' width={400} height={400}/>
        <Image src='/421.gif' width={400} height={400}/>
        <Image src='/1424.gif' width={400} height={400}/>
        <Image src='/1581.gif' width={400} height={400}/>
        <Image src='/1824.gif' width={400} height={400}/>
      </div>

    <div style={{backgroundColor:"bisque"}}>

      <div className={styles.other}>
        <div>
        <div className={styles.gridimage}>
          <Image src='/firesnowhouse.gif' width={400} height={400} className="rounded" style={{borderRadius: "20px", boxShadow:"-4px -3px 45px 21px rgba(0,0,0,0.35)"}}/>
          </div>  
        </div>
        <div>  
          <div className={styles.griditem}  style={{textAlign:"left"}}>
            <h1 style={{borderBottom:"2px solid black"}}>
              Sample Title
            </h1>
            <p style={{fontFamily:"ChronoType"}}> 
            TThe Missouri Centennial half dollar is a commemorative fifty-cent piece struck by the United States Mint in 1921. It was designed by Robert Ingersoll Aitken. The US state of Missouri wanted a commemorative coin to mark its centennial that year. Legislation for such a coin passed through Congress without opposition and was signed on March 4, 1921 by President Warren G. Harding on his inauguration day. The federal Commission of Fine Arts hired Aitken to design the coin, which depicted Daniel Boone on both sides. The reverse design, showing Boone with a Native American, was likely intended to symbolize the displacement of the Indians by white settlers.he Missouri Centennial half dollar is a commemorative fifty-cent piece struck by the United States Mint in 1921. It was designed by Robert Ing
            </p>
          </div>  
        </div>
      </div>
      

    
      <div className={styles.other} style={{}}>
        <div style={{}}>
          <div className={styles.griditem} style={{textAlign:"right"}}>
            <h1 style={{borderBottom:"2px solid black"}}>
              Sameple Title
            </h1>
            <p>
            <div style={{fontFamily:"ChronoType"}}>
        Sample Text
        </div>
            </p>
          </div>
        </div>
        <div>  
          <div  style={{}} className={styles.gridimage}>
          <Image src='/abandonedhouse.png' width={400} height={400} className="rounded" style={{borderRadius: "20px", boxShadow:"-4px -3px 45px 21px rgba(0,0,0,0.35)"}}/>
          </div>  
        </div>
        </div>

        </div>
    </div>
  )
}


