import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Map() {

    return (
      <div>
        <Head>
            <title>Pixieland | Map </title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
      <main className={styles.main2}>

      </main>
      </div>  
      </div>
    )
  }