import Head from 'next/head'
import { Container, Row, Col} from "react-bootstrap";
import styles from '../styles/Home.module.css'

export default function Mint() {

    function numbcount(){
        console.log("Hi")
    }

    return (
      <div className={styles.main2}>
        <Head>
            <title>Pixieland | Mint</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

          <h1>MINT</h1>
          
          <div style={{border: "2px solid #eaeaea", height:"600px", width:"1350px", display:"inline-flex", backgroundColor:"blueviolet", alignItems:"center", justifyContent:"center"}}>

            <div className={styles.grad} style={{border: "10px solid #eaeaea", height:"550px", width:"400px", margin:"20px"}}>
              <h2 style={{alignItems:"center", justifyContent:"center", display:"flex"}}>Land</h2>
              <img style={{alignItems:"center", paddingInline:"50px"}} src='character.png'/>
              <p style={{alignItems:"center", justifyContent:"center", display:"flex"}}>0/1000</p>
              <p style={{alignItems:"center", justifyContent:"center", display:"flex"}}>MINT</p>
            </div>

            <div className={styles.grad2} style={{border: "10px solid #eaeaea", height:"550px", width:"400px", margin:"20px"}}>
                <h2 style={{alignItems:"center", justifyContent:"center", display:"flex"}}>Houses</h2>
              <img style={{alignItems:"center", paddingInline:"50px"}} src='character.png'/>
              <p style={{alignItems:"center", justifyContent:"center", display:"flex"}}>0/2000</p>
              <p style={{alignItems:"center", justifyContent:"center", display:"flex"}}>MINT</p>
            </div>

            <div className={styles.grad3} style={{border: "10px solid #eaeaea", height:"550px", width:"400px", margin:"20px"}}>
                <h2 style={{alignItems:"center", justifyContent:"center", display:"flex"}}>Characters</h2>
              <img style={{alignItems:"center", paddingInline:"50px"}} src='character.png'/>
              <p style={{alignItems:"center", justifyContent:"center", display:"flex"}}>0/3000</p>
              <p style={{alignItems:"center", justifyContent:"center", display:"flex"}}>MINT</p>
            </div>

          </div>
      </div>
    )
  }