import Head from 'next/head'
import { Container, Row, Col} from "react-bootstrap";
import styles from '../styles/Home.module.css'

export default function Mint() {

    function numbcount(){
        console.log("Hi")
    }

    return (
      <div className={styles.container}>
        <Head>
            <title>Pixieland | Mint</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        
      <div>
      <main className={styles.main2}>
        <h1 className={styles.minttitle} >
        <a>Mint your very own pixiehouse!</a>
        </h1>
        <h2>
          <div>
            <button style={{borderRadius:"10px", backgroundColor:"#F96D87", color:"white", fontWeight:"bold", padding:"10px 30px 10px 30px", border:"0px"}}>
              MINT
            </button>
          </div>
        </h2>
      </main>
      </div>          
      
      </div>
    )
  }