import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Whitepaper() {

    return (
      <div>
        <Head>
            <title>Pixieland | Whitepaper</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/Borboleta.jpg" />
        </Head>
        <div>
          <main className={styles.main3}>
            <h1 className={styles.title} style={{paddingTop:"20px"}}>Whitepaper</h1>
            <p style={{textAlign:"left"}}>Whitepaper text</p>
          </main>
        </div>  
      </div>
    
    )
  }